name: Build & Update on Release

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch: # Super wichtig zum Testen!
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Code vom Haupt-Branch herunterladen
        uses: actions/checkout@v4
        with:
          # Erkennt automatisch, ob du 'main' oder 'master' nutzt!
          ref: ${{ github.event.repository.default_branch }}

      - name: Version aus .ino extrahierten
        run: |
          VERSION=$(grep 'String firmware_version' Arduino/insane_bl_v5.ino | cut -d'"' -f2)
          echo "Gefundene Version im Code: $VERSION"
          mkdir -p Firmware
          echo "$VERSION" > Firmware/version.txt

      - name: Arduino Sketch kompilieren
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32
          platforms: |
            - name: esp32:esp32
              source-url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
          libraries: |
            - source-url: https://github.com/pschatzmann/ESP32-A2DP.git
          sketch-paths: |
            - Arduino/insane_bl_v5.ino
          cli-compile-flags: |
            - --export-binaries

      - name: Merged Bin kopieren
        run: |
          find Arduino/build -name "*.merged.bin" -exec cp {} Firmware/insane_bl_v5.ino.merged.bin \;

      - name: Neue Dateien ins Repository pushen
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add Firmware/insane_bl_v5.ino.merged.bin
          git add Firmware/version.txt
          
          # Wir fangen Fehler ab, falls sich die Dateien mal nicht geändert haben sollten
          git commit -m "Auto-Update: Firmware & version.txt für Release aktualisiert" || echo "Keine Änderungen zum Committen gefunden."
          
          # Der wichtigste Teil: Wir zwingen Git, auf den richtigen Haupt-Zweig zu pushen!
          git push origin HEAD:${{ github.event.repository.default_branch }}
